### ISSUE TITLE
Can u also provide the prediction code how to predict after the model is trained, also kindly share trained model

### ISSUE THREAD

**Issue by raviyellani** [valots12/video-activity-recognition#1]

**Comment by valots12** [comment]
Hi,
you can use the function keras.models.load_model('path/to/location') to load the model and model.predict() to make new predictions.

I just upload the two models.

**Comment by raviyellani** [comment]
I am new to ML can u please share a sample code how to do the predictions by load the this model

**Comment by valots12** [comment]
Try to read this source about Keras, it is easily explained: https://towardsdatascience.com/how-to-predict-an-image-with-keras-ca97d9cd4817

**Comment by raviyellani** [comment]
Sorry for bothering you , but i can not able to implement it . So kindly please share the prediction code how the input has to be provided and display prediction output. Thank you in advance

**Comment by valots12** [comment]
This code should work properly:

model = keras.models.load_model('path/to/location')
test_output = model.predict(features_test, verbose=0)
print(test_output)

**Comment by raviyellani** [comment]
I am getting this error 
/////////////////////////// PREDICTION CODE ////////////////////
from tensorflow import keras
import numpy as np
import tensorflow as tf
from tensorflow import keras

from keras.models import load_model


model = keras.models.load_model('MoveNet.h5')
test_output = model.predict("video.mp4", verbose=0)
print(test_output)


///////////////////////// ERROR               /////////////
Traceback (most recent call last):
  File "D:\actionrecognition\video-activity-recognition-main\models\test.py", line 10, in <module>
    test_output = model.predict("video.mp4", verbose=0)
  File "C:\Users\raviy\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\raviy\anaconda3\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 906, in __getitem__
    return self._dims[key]
IndexError: tuple index out of range

**Comment by valots12** [comment]
The code is okay; you have to pass as input to the predict() function only a limited number of frames of the sample video. You can use the frames_extraction() function to automate this process.
